#!/bin/bash

# Sync Setup Script
# Auto-generated by master-sync-setup.sh

set -e

# Configuration
GDRIVE_ROOT="$HOME/My Drive/dev-sync"
REPO_NAME=$(basename $(git rev-parse --show-toplevel 2>/dev/null || pwd))
SYNC_DIR="$GDRIVE_ROOT/$REPO_NAME"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo "Setting up sync for: $REPO_NAME"
echo "Sync directory: $SYNC_DIR"
echo ""

# Create Google Drive directory
mkdir -p "$SYNC_DIR"

# Files/directories to sync
SYNC_ITEMS=(
    "vendor"
)

# Create symlinks
for item in "${SYNC_ITEMS[@]}"; do
    # Skip if empty
    [ -z "$item" ] && continue
    
    # Create parent directory in repo if needed
    parent=$(dirname "$item")
    if [ "$parent" != "." ]; then
        mkdir -p "$parent"
    fi
    
    # Create directory in Google Drive if item ends with / or if it's a directory
    mkdir -p "$SYNC_DIR/$(dirname "$item")"
    
    # Remove existing symlink if it exists
    if [ -L "$item" ]; then
        rm "$item"
        echo -e "${YELLOW}⚠${NC}  Removed existing symlink: $item"
    fi
    
    # Skip if actual file/directory already exists (don't overwrite)
    if [ -e "$item" ] && [ ! -L "$item" ]; then
        echo -e "${YELLOW}⚠${NC}  Skipping $item (already exists, not a symlink)"
        echo "    To sync, manually move to: $SYNC_DIR/$item"
        continue
    fi
    
    # Create symlink
    ln -s "$SYNC_DIR/$item" "$item"
    echo -e "${GREEN}✓${NC} Created symlink: $item -> $SYNC_DIR/$item"
done

echo ""
echo -e "${GREEN}Sync setup complete!${NC}"
echo ""
echo "Next steps:"
echo "1. Move your git-ignored files to: $SYNC_DIR/"
echo "2. They will automatically sync via Google Drive"
echo "3. Run this script again on your Linux machine after cloning"
